## Machine Learning (CMSC 197) Quiz 1

<h4>Emmanuel Tarek Shayne Guides, September 24, 2022</h4>

## 

## Part 1

## Starting off by initializing both arrays

In [3]:
import numpy as np

# Initialize arrays y_hat (20 linearly spaced numbers from -1 to 1) 
# and y (20 linearly spaced numbers between 0 and 1)

y_hat = np.linspace(-1, 1, 20)
y = np.linspace(0, 1, 20)

print("y_hat:\n", y_hat, "\n\n\n", "y:\n", y)

y_hat:
 [-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ] 


 y:
 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## y_hat and y dimensions and shapes

In [6]:
# checking for y and y_hat dimensions
yDimension = y.ndim
y_hatDimension = y_hat.ndim

# checking for y and y_hat shapes
yShape = y.shape
y_hatShape = y_hat.shape

print("y dimension: ",yDimension ,"\ny_hat dimension: ",y_hatDimension)
print("\ny shape: ", yShape, "\ny_hat shape: ", y_hatShape)

y dimension:  1 
y_hat dimension:  1

y shape:  (20,) 
y_hat shape:  (20,)


## Mean Squared Error

In [33]:
# solving for the mean squared error
# we can use a for loop
l_mse = 0
for i in range(len(y)):
    l_mse = l_mse + (y_hat[i] - y[i])**2
print("MSE using for loop: \t", l_mse / len(y))

# we can also use numpy
l_mse_np = (np.square(np.subtract(y, y_hat))).mean()
print("MSE using numpy: \t", l_mse_np)



MSE using for loop: 	 0.34210526315789475
MSE using numpy: 	 0.3421052631578948


## Mean Absolute Error

In [30]:
# solving for the mean absolute error

l_mae = 0
for i in range(len(y)):
    l_mae = l_mae + (abs(y_hat[i] - y[i]))
print("Mean absolute error is around:", l_mae / len(y))

Mean absolute error is around: 0.5000000000000001


## Mean Squared Logarithmic Error

In [34]:
import math

l_msl = 0
for i in range(len(y)):
    l_msl = l_msl + (math.log((y_hat[i] + 1)) - math.log(y[i] + 1))**2
print("L MSL is: ", l_msl / len(y))

ValueError: math domain error

for the above (MSLE), I did not opt to cut the y_hat array since that is what the data is. Additionally, the error here honesly is just because of the first element in the y_hat array which is -1. Even if we add 1 to it, the result, 0, would still produce an error if we try to get its log.

## Mean Absolute Percentage Error

In [50]:
l_mape = 0
for i in range(len(y)):
    l_mape = l_mape + (abs((y_hat[i] - y[i]) / y[i]))
    
print((1/len(y)*l_mape))

inf


C:\Users\Emmanuel Guides\AppData\Local\Temp\ipykernel_8684\2573523413.py:3: RuntimeWarning: divide by zero encountered in double_scalars
  l_mape = l_mape + (abs((y_hat[i] - y[i]) / y[i]))


In the mean absolute percentage error, we encounter an error that reads 'divide by zero'. This is because in the y array the first element is 0. 

## 

## Part 2

Creating 1d Array M using arange

In [52]:
# Creating 1D M array that has elements 1 to 16
M = np.arange(1, 17)
print(M)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


## 

Reshaping M into a 4x4 array and storing it to N

In [54]:
# Reshaping M
N = M.reshape(4, 4)
print(N)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## 

Getting the 2nd row of N

In [62]:
print(N[1,0:])

[5 6 7 8]


## 

Getting the minimum values for each column of N

In [67]:
for i in range(4):
    print("Min Value of column ", i,"(", 
          N[0:,i], "): ", min(N[0:,i]))

Min Value of column  0 ( [ 1  5  9 13] ):  1
Min Value of column  1 ( [ 2  6 10 14] ):  2
Min Value of column  2 ( [ 3  7 11 15] ):  3
Min Value of column  3 ( [ 4  8 12 16] ):  4


## 

Getting the locations of the minimum values of each column of N

In [73]:
for i in range(4):
    print("Min Value of column ", i, " is ", min(N[0:,i]), 
          ", location: ", np.argwhere(N == min(N[0:,i])))

Min Value of column  0  is  1 , location:  [[0 0]]
Min Value of column  1  is  2 , location:  [[0 1]]
Min Value of column  2  is  3 , location:  [[0 2]]
Min Value of column  3  is  4 , location:  [[0 3]]


## 

Getting the average of the whole N matrix

In [75]:
print(N.mean())

8.5


## 

Creating Vector V

In [77]:
V = np.array([1,1,1,1])
print(V)

[1 1 1 1]


## 

Taking the dot product of N and V

In [80]:
print(np.dot(N,V))

[10 26 42 58]
